"""Creacion de Vehiculo

Revision ID: 01343f560ebc
Revises: c9fc4931532d
Create Date: 2024-07-21 19:59:40.729957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01343f560ebc'
down_revision = 'c9fc4931532d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('anio_fabricacion', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculo')
    # ### end Alembic commands ###
